// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TrackedRepo is the predicate function for trackedrepo builders.
type TrackedRepo func(*sql.Selector)
