// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ilyas/repository-tracker-app/backend/ent/schema"
	"github.com/ilyas/repository-tracker-app/backend/ent/trackedrepo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	trackedrepoFields := schema.TrackedRepo{}.Fields()
	_ = trackedrepoFields
	// trackedrepoDescOwner is the schema descriptor for owner field.
	trackedrepoDescOwner := trackedrepoFields[0].Descriptor()
	// trackedrepo.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	trackedrepo.OwnerValidator = func() func(string) error {
		validators := trackedrepoDescOwner.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(owner string) error {
			for _, fn := range fns {
				if err := fn(owner); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// trackedrepoDescName is the schema descriptor for name field.
	trackedrepoDescName := trackedrepoFields[1].Descriptor()
	// trackedrepo.NameValidator is a validator for the "name" field. It is called by the builders before save.
	trackedrepo.NameValidator = func() func(string) error {
		validators := trackedrepoDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// trackedrepoDescFullName is the schema descriptor for full_name field.
	trackedrepoDescFullName := trackedrepoFields[2].Descriptor()
	// trackedrepo.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	trackedrepo.FullNameValidator = func() func(string) error {
		validators := trackedrepoDescFullName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(full_name string) error {
			for _, fn := range fns {
				if err := fn(full_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// trackedrepoDescDescription is the schema descriptor for description field.
	trackedrepoDescDescription := trackedrepoFields[3].Descriptor()
	// trackedrepo.DefaultDescription holds the default value on creation for the description field.
	trackedrepo.DefaultDescription = trackedrepoDescDescription.Default.(string)
	// trackedrepo.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	trackedrepo.DescriptionValidator = trackedrepoDescDescription.Validators[0].(func(string) error)
	// trackedrepoDescStars is the schema descriptor for stars field.
	trackedrepoDescStars := trackedrepoFields[4].Descriptor()
	// trackedrepo.DefaultStars holds the default value on creation for the stars field.
	trackedrepo.DefaultStars = trackedrepoDescStars.Default.(int)
	// trackedrepo.StarsValidator is a validator for the "stars" field. It is called by the builders before save.
	trackedrepo.StarsValidator = trackedrepoDescStars.Validators[0].(func(int) error)
	// trackedrepoDescLanguage is the schema descriptor for language field.
	trackedrepoDescLanguage := trackedrepoFields[5].Descriptor()
	// trackedrepo.DefaultLanguage holds the default value on creation for the language field.
	trackedrepo.DefaultLanguage = trackedrepoDescLanguage.Default.(string)
	// trackedrepoDescHTMLURL is the schema descriptor for html_url field.
	trackedrepoDescHTMLURL := trackedrepoFields[6].Descriptor()
	// trackedrepo.HTMLURLValidator is a validator for the "html_url" field. It is called by the builders before save.
	trackedrepo.HTMLURLValidator = trackedrepoDescHTMLURL.Validators[0].(func(string) error)
	// trackedrepoDescNotes is the schema descriptor for notes field.
	trackedrepoDescNotes := trackedrepoFields[7].Descriptor()
	// trackedrepo.DefaultNotes holds the default value on creation for the notes field.
	trackedrepo.DefaultNotes = trackedrepoDescNotes.Default.(string)
	// trackedrepo.NotesValidator is a validator for the "notes" field. It is called by the builders before save.
	trackedrepo.NotesValidator = trackedrepoDescNotes.Validators[0].(func(string) error)
	// trackedrepoDescFetchedAt is the schema descriptor for fetched_at field.
	trackedrepoDescFetchedAt := trackedrepoFields[8].Descriptor()
	// trackedrepo.DefaultFetchedAt holds the default value on creation for the fetched_at field.
	trackedrepo.DefaultFetchedAt = trackedrepoDescFetchedAt.Default.(func() time.Time)
	// trackedrepoDescCreatedAt is the schema descriptor for created_at field.
	trackedrepoDescCreatedAt := trackedrepoFields[9].Descriptor()
	// trackedrepo.DefaultCreatedAt holds the default value on creation for the created_at field.
	trackedrepo.DefaultCreatedAt = trackedrepoDescCreatedAt.Default.(func() time.Time)
	// trackedrepoDescUpdatedAt is the schema descriptor for updated_at field.
	trackedrepoDescUpdatedAt := trackedrepoFields[10].Descriptor()
	// trackedrepo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	trackedrepo.DefaultUpdatedAt = trackedrepoDescUpdatedAt.Default.(func() time.Time)
	// trackedrepo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	trackedrepo.UpdateDefaultUpdatedAt = trackedrepoDescUpdatedAt.UpdateDefault.(func() time.Time)
}
