// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ilyas/repository-tracker-app/backend/ent/predicate"
	"github.com/ilyas/repository-tracker-app/backend/ent/trackedrepo"
)

// TrackedRepoDelete is the builder for deleting a TrackedRepo entity.
type TrackedRepoDelete struct {
	config
	hooks    []Hook
	mutation *TrackedRepoMutation
}

// Where appends a list predicates to the TrackedRepoDelete builder.
func (trd *TrackedRepoDelete) Where(ps ...predicate.TrackedRepo) *TrackedRepoDelete {
	trd.mutation.Where(ps...)
	return trd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trd *TrackedRepoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, trd.sqlExec, trd.mutation, trd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (trd *TrackedRepoDelete) ExecX(ctx context.Context) int {
	n, err := trd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trd *TrackedRepoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(trackedrepo.Table, sqlgraph.NewFieldSpec(trackedrepo.FieldID, field.TypeInt))
	if ps := trd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, trd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	trd.mutation.done = true
	return affected, err
}

// TrackedRepoDeleteOne is the builder for deleting a single TrackedRepo entity.
type TrackedRepoDeleteOne struct {
	trd *TrackedRepoDelete
}

// Where appends a list predicates to the TrackedRepoDelete builder.
func (trdo *TrackedRepoDeleteOne) Where(ps ...predicate.TrackedRepo) *TrackedRepoDeleteOne {
	trdo.trd.mutation.Where(ps...)
	return trdo
}

// Exec executes the deletion query.
func (trdo *TrackedRepoDeleteOne) Exec(ctx context.Context) error {
	n, err := trdo.trd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trackedrepo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trdo *TrackedRepoDeleteOne) ExecX(ctx context.Context) {
	if err := trdo.Exec(ctx); err != nil {
		panic(err)
	}
}
