// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ilyas/repository-tracker-app/backend/ent/trackedrepo"
)

// TrackedRepoCreate is the builder for creating a TrackedRepo entity.
type TrackedRepoCreate struct {
	config
	mutation *TrackedRepoMutation
	hooks    []Hook
}

// SetOwner sets the "owner" field.
func (trc *TrackedRepoCreate) SetOwner(s string) *TrackedRepoCreate {
	trc.mutation.SetOwner(s)
	return trc
}

// SetName sets the "name" field.
func (trc *TrackedRepoCreate) SetName(s string) *TrackedRepoCreate {
	trc.mutation.SetName(s)
	return trc
}

// SetFullName sets the "full_name" field.
func (trc *TrackedRepoCreate) SetFullName(s string) *TrackedRepoCreate {
	trc.mutation.SetFullName(s)
	return trc
}

// SetDescription sets the "description" field.
func (trc *TrackedRepoCreate) SetDescription(s string) *TrackedRepoCreate {
	trc.mutation.SetDescription(s)
	return trc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableDescription(s *string) *TrackedRepoCreate {
	if s != nil {
		trc.SetDescription(*s)
	}
	return trc
}

// SetStars sets the "stars" field.
func (trc *TrackedRepoCreate) SetStars(i int) *TrackedRepoCreate {
	trc.mutation.SetStars(i)
	return trc
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableStars(i *int) *TrackedRepoCreate {
	if i != nil {
		trc.SetStars(*i)
	}
	return trc
}

// SetForks sets the "forks" field.
func (trc *TrackedRepoCreate) SetForks(i int) *TrackedRepoCreate {
	trc.mutation.SetForks(i)
	return trc
}

// SetNillableForks sets the "forks" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableForks(i *int) *TrackedRepoCreate {
	if i != nil {
		trc.SetForks(*i)
	}
	return trc
}

// SetLanguage sets the "language" field.
func (trc *TrackedRepoCreate) SetLanguage(s string) *TrackedRepoCreate {
	trc.mutation.SetLanguage(s)
	return trc
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableLanguage(s *string) *TrackedRepoCreate {
	if s != nil {
		trc.SetLanguage(*s)
	}
	return trc
}

// SetHTMLURL sets the "html_url" field.
func (trc *TrackedRepoCreate) SetHTMLURL(s string) *TrackedRepoCreate {
	trc.mutation.SetHTMLURL(s)
	return trc
}

// SetNotes sets the "notes" field.
func (trc *TrackedRepoCreate) SetNotes(s string) *TrackedRepoCreate {
	trc.mutation.SetNotes(s)
	return trc
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableNotes(s *string) *TrackedRepoCreate {
	if s != nil {
		trc.SetNotes(*s)
	}
	return trc
}

// SetFetchedAt sets the "fetched_at" field.
func (trc *TrackedRepoCreate) SetFetchedAt(t time.Time) *TrackedRepoCreate {
	trc.mutation.SetFetchedAt(t)
	return trc
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableFetchedAt(t *time.Time) *TrackedRepoCreate {
	if t != nil {
		trc.SetFetchedAt(*t)
	}
	return trc
}

// SetCreatedAt sets the "created_at" field.
func (trc *TrackedRepoCreate) SetCreatedAt(t time.Time) *TrackedRepoCreate {
	trc.mutation.SetCreatedAt(t)
	return trc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableCreatedAt(t *time.Time) *TrackedRepoCreate {
	if t != nil {
		trc.SetCreatedAt(*t)
	}
	return trc
}

// SetUpdatedAt sets the "updated_at" field.
func (trc *TrackedRepoCreate) SetUpdatedAt(t time.Time) *TrackedRepoCreate {
	trc.mutation.SetUpdatedAt(t)
	return trc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (trc *TrackedRepoCreate) SetNillableUpdatedAt(t *time.Time) *TrackedRepoCreate {
	if t != nil {
		trc.SetUpdatedAt(*t)
	}
	return trc
}

// Mutation returns the TrackedRepoMutation object of the builder.
func (trc *TrackedRepoCreate) Mutation() *TrackedRepoMutation {
	return trc.mutation
}

// Save creates the TrackedRepo in the database.
func (trc *TrackedRepoCreate) Save(ctx context.Context) (*TrackedRepo, error) {
	trc.defaults()
	return withHooks(ctx, trc.sqlSave, trc.mutation, trc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (trc *TrackedRepoCreate) SaveX(ctx context.Context) *TrackedRepo {
	v, err := trc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trc *TrackedRepoCreate) Exec(ctx context.Context) error {
	_, err := trc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trc *TrackedRepoCreate) ExecX(ctx context.Context) {
	if err := trc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (trc *TrackedRepoCreate) defaults() {
	if _, ok := trc.mutation.Description(); !ok {
		v := trackedrepo.DefaultDescription
		trc.mutation.SetDescription(v)
	}
	if _, ok := trc.mutation.Stars(); !ok {
		v := trackedrepo.DefaultStars
		trc.mutation.SetStars(v)
	}
	if _, ok := trc.mutation.Forks(); !ok {
		v := trackedrepo.DefaultForks
		trc.mutation.SetForks(v)
	}
	if _, ok := trc.mutation.Language(); !ok {
		v := trackedrepo.DefaultLanguage
		trc.mutation.SetLanguage(v)
	}
	if _, ok := trc.mutation.Notes(); !ok {
		v := trackedrepo.DefaultNotes
		trc.mutation.SetNotes(v)
	}
	if _, ok := trc.mutation.FetchedAt(); !ok {
		v := trackedrepo.DefaultFetchedAt()
		trc.mutation.SetFetchedAt(v)
	}
	if _, ok := trc.mutation.CreatedAt(); !ok {
		v := trackedrepo.DefaultCreatedAt()
		trc.mutation.SetCreatedAt(v)
	}
	if _, ok := trc.mutation.UpdatedAt(); !ok {
		v := trackedrepo.DefaultUpdatedAt()
		trc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (trc *TrackedRepoCreate) check() error {
	if _, ok := trc.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "TrackedRepo.owner"`)}
	}
	if v, ok := trc.mutation.Owner(); ok {
		if err := trackedrepo.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.owner": %w`, err)}
		}
	}
	if _, ok := trc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TrackedRepo.name"`)}
	}
	if v, ok := trc.mutation.Name(); ok {
		if err := trackedrepo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.name": %w`, err)}
		}
	}
	if _, ok := trc.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "TrackedRepo.full_name"`)}
	}
	if v, ok := trc.mutation.FullName(); ok {
		if err := trackedrepo.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.full_name": %w`, err)}
		}
	}
	if v, ok := trc.mutation.Description(); ok {
		if err := trackedrepo.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.description": %w`, err)}
		}
	}
	if _, ok := trc.mutation.Stars(); !ok {
		return &ValidationError{Name: "stars", err: errors.New(`ent: missing required field "TrackedRepo.stars"`)}
	}
	if v, ok := trc.mutation.Stars(); ok {
		if err := trackedrepo.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.stars": %w`, err)}
		}
	}
	if _, ok := trc.mutation.Forks(); !ok {
		return &ValidationError{Name: "forks", err: errors.New(`ent: missing required field "TrackedRepo.forks"`)}
	}
	if v, ok := trc.mutation.Forks(); ok {
		if err := trackedrepo.ForksValidator(v); err != nil {
			return &ValidationError{Name: "forks", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.forks": %w`, err)}
		}
	}
	if _, ok := trc.mutation.HTMLURL(); !ok {
		return &ValidationError{Name: "html_url", err: errors.New(`ent: missing required field "TrackedRepo.html_url"`)}
	}
	if v, ok := trc.mutation.HTMLURL(); ok {
		if err := trackedrepo.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.html_url": %w`, err)}
		}
	}
	if v, ok := trc.mutation.Notes(); ok {
		if err := trackedrepo.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.notes": %w`, err)}
		}
	}
	if _, ok := trc.mutation.FetchedAt(); !ok {
		return &ValidationError{Name: "fetched_at", err: errors.New(`ent: missing required field "TrackedRepo.fetched_at"`)}
	}
	if _, ok := trc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TrackedRepo.created_at"`)}
	}
	if _, ok := trc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TrackedRepo.updated_at"`)}
	}
	return nil
}

func (trc *TrackedRepoCreate) sqlSave(ctx context.Context) (*TrackedRepo, error) {
	if err := trc.check(); err != nil {
		return nil, err
	}
	_node, _spec := trc.createSpec()
	if err := sqlgraph.CreateNode(ctx, trc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	trc.mutation.id = &_node.ID
	trc.mutation.done = true
	return _node, nil
}

func (trc *TrackedRepoCreate) createSpec() (*TrackedRepo, *sqlgraph.CreateSpec) {
	var (
		_node = &TrackedRepo{config: trc.config}
		_spec = sqlgraph.NewCreateSpec(trackedrepo.Table, sqlgraph.NewFieldSpec(trackedrepo.FieldID, field.TypeInt))
	)
	if value, ok := trc.mutation.Owner(); ok {
		_spec.SetField(trackedrepo.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := trc.mutation.Name(); ok {
		_spec.SetField(trackedrepo.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := trc.mutation.FullName(); ok {
		_spec.SetField(trackedrepo.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := trc.mutation.Description(); ok {
		_spec.SetField(trackedrepo.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := trc.mutation.Stars(); ok {
		_spec.SetField(trackedrepo.FieldStars, field.TypeInt, value)
		_node.Stars = value
	}
	if value, ok := trc.mutation.Forks(); ok {
		_spec.SetField(trackedrepo.FieldForks, field.TypeInt, value)
		_node.Forks = value
	}
	if value, ok := trc.mutation.Language(); ok {
		_spec.SetField(trackedrepo.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := trc.mutation.HTMLURL(); ok {
		_spec.SetField(trackedrepo.FieldHTMLURL, field.TypeString, value)
		_node.HTMLURL = value
	}
	if value, ok := trc.mutation.Notes(); ok {
		_spec.SetField(trackedrepo.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := trc.mutation.FetchedAt(); ok {
		_spec.SetField(trackedrepo.FieldFetchedAt, field.TypeTime, value)
		_node.FetchedAt = value
	}
	if value, ok := trc.mutation.CreatedAt(); ok {
		_spec.SetField(trackedrepo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := trc.mutation.UpdatedAt(); ok {
		_spec.SetField(trackedrepo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TrackedRepoCreateBulk is the builder for creating many TrackedRepo entities in bulk.
type TrackedRepoCreateBulk struct {
	config
	err      error
	builders []*TrackedRepoCreate
}

// Save creates the TrackedRepo entities in the database.
func (trcb *TrackedRepoCreateBulk) Save(ctx context.Context) ([]*TrackedRepo, error) {
	if trcb.err != nil {
		return nil, trcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(trcb.builders))
	nodes := make([]*TrackedRepo, len(trcb.builders))
	mutators := make([]Mutator, len(trcb.builders))
	for i := range trcb.builders {
		func(i int, root context.Context) {
			builder := trcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrackedRepoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, trcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, trcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, trcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (trcb *TrackedRepoCreateBulk) SaveX(ctx context.Context) []*TrackedRepo {
	v, err := trcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trcb *TrackedRepoCreateBulk) Exec(ctx context.Context) error {
	_, err := trcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trcb *TrackedRepoCreateBulk) ExecX(ctx context.Context) {
	if err := trcb.Exec(ctx); err != nil {
		panic(err)
	}
}
