// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ilyas/repository-tracker-app/backend/ent/predicate"
	"github.com/ilyas/repository-tracker-app/backend/ent/trackedrepo"
)

// TrackedRepoUpdate is the builder for updating TrackedRepo entities.
type TrackedRepoUpdate struct {
	config
	hooks    []Hook
	mutation *TrackedRepoMutation
}

// Where appends a list predicates to the TrackedRepoUpdate builder.
func (tru *TrackedRepoUpdate) Where(ps ...predicate.TrackedRepo) *TrackedRepoUpdate {
	tru.mutation.Where(ps...)
	return tru
}

// SetOwner sets the "owner" field.
func (tru *TrackedRepoUpdate) SetOwner(s string) *TrackedRepoUpdate {
	tru.mutation.SetOwner(s)
	return tru
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableOwner(s *string) *TrackedRepoUpdate {
	if s != nil {
		tru.SetOwner(*s)
	}
	return tru
}

// SetName sets the "name" field.
func (tru *TrackedRepoUpdate) SetName(s string) *TrackedRepoUpdate {
	tru.mutation.SetName(s)
	return tru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableName(s *string) *TrackedRepoUpdate {
	if s != nil {
		tru.SetName(*s)
	}
	return tru
}

// SetFullName sets the "full_name" field.
func (tru *TrackedRepoUpdate) SetFullName(s string) *TrackedRepoUpdate {
	tru.mutation.SetFullName(s)
	return tru
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableFullName(s *string) *TrackedRepoUpdate {
	if s != nil {
		tru.SetFullName(*s)
	}
	return tru
}

// SetDescription sets the "description" field.
func (tru *TrackedRepoUpdate) SetDescription(s string) *TrackedRepoUpdate {
	tru.mutation.SetDescription(s)
	return tru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableDescription(s *string) *TrackedRepoUpdate {
	if s != nil {
		tru.SetDescription(*s)
	}
	return tru
}

// ClearDescription clears the value of the "description" field.
func (tru *TrackedRepoUpdate) ClearDescription() *TrackedRepoUpdate {
	tru.mutation.ClearDescription()
	return tru
}

// SetStars sets the "stars" field.
func (tru *TrackedRepoUpdate) SetStars(i int) *TrackedRepoUpdate {
	tru.mutation.ResetStars()
	tru.mutation.SetStars(i)
	return tru
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableStars(i *int) *TrackedRepoUpdate {
	if i != nil {
		tru.SetStars(*i)
	}
	return tru
}

// AddStars adds i to the "stars" field.
func (tru *TrackedRepoUpdate) AddStars(i int) *TrackedRepoUpdate {
	tru.mutation.AddStars(i)
	return tru
}

// SetForks sets the "forks" field.
func (tru *TrackedRepoUpdate) SetForks(i int) *TrackedRepoUpdate {
	tru.mutation.ResetForks()
	tru.mutation.SetForks(i)
	return tru
}

// SetNillableForks sets the "forks" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableForks(i *int) *TrackedRepoUpdate {
	if i != nil {
		tru.SetForks(*i)
	}
	return tru
}

// AddForks adds i to the "forks" field.
func (tru *TrackedRepoUpdate) AddForks(i int) *TrackedRepoUpdate {
	tru.mutation.AddForks(i)
	return tru
}

// SetLanguage sets the "language" field.
func (tru *TrackedRepoUpdate) SetLanguage(s string) *TrackedRepoUpdate {
	tru.mutation.SetLanguage(s)
	return tru
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableLanguage(s *string) *TrackedRepoUpdate {
	if s != nil {
		tru.SetLanguage(*s)
	}
	return tru
}

// ClearLanguage clears the value of the "language" field.
func (tru *TrackedRepoUpdate) ClearLanguage() *TrackedRepoUpdate {
	tru.mutation.ClearLanguage()
	return tru
}

// SetHTMLURL sets the "html_url" field.
func (tru *TrackedRepoUpdate) SetHTMLURL(s string) *TrackedRepoUpdate {
	tru.mutation.SetHTMLURL(s)
	return tru
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableHTMLURL(s *string) *TrackedRepoUpdate {
	if s != nil {
		tru.SetHTMLURL(*s)
	}
	return tru
}

// SetNotes sets the "notes" field.
func (tru *TrackedRepoUpdate) SetNotes(s string) *TrackedRepoUpdate {
	tru.mutation.SetNotes(s)
	return tru
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableNotes(s *string) *TrackedRepoUpdate {
	if s != nil {
		tru.SetNotes(*s)
	}
	return tru
}

// ClearNotes clears the value of the "notes" field.
func (tru *TrackedRepoUpdate) ClearNotes() *TrackedRepoUpdate {
	tru.mutation.ClearNotes()
	return tru
}

// SetFetchedAt sets the "fetched_at" field.
func (tru *TrackedRepoUpdate) SetFetchedAt(t time.Time) *TrackedRepoUpdate {
	tru.mutation.SetFetchedAt(t)
	return tru
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (tru *TrackedRepoUpdate) SetNillableFetchedAt(t *time.Time) *TrackedRepoUpdate {
	if t != nil {
		tru.SetFetchedAt(*t)
	}
	return tru
}

// SetUpdatedAt sets the "updated_at" field.
func (tru *TrackedRepoUpdate) SetUpdatedAt(t time.Time) *TrackedRepoUpdate {
	tru.mutation.SetUpdatedAt(t)
	return tru
}

// Mutation returns the TrackedRepoMutation object of the builder.
func (tru *TrackedRepoUpdate) Mutation() *TrackedRepoMutation {
	return tru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tru *TrackedRepoUpdate) Save(ctx context.Context) (int, error) {
	tru.defaults()
	return withHooks(ctx, tru.sqlSave, tru.mutation, tru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tru *TrackedRepoUpdate) SaveX(ctx context.Context) int {
	affected, err := tru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tru *TrackedRepoUpdate) Exec(ctx context.Context) error {
	_, err := tru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tru *TrackedRepoUpdate) ExecX(ctx context.Context) {
	if err := tru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tru *TrackedRepoUpdate) defaults() {
	if _, ok := tru.mutation.UpdatedAt(); !ok {
		v := trackedrepo.UpdateDefaultUpdatedAt()
		tru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tru *TrackedRepoUpdate) check() error {
	if v, ok := tru.mutation.Owner(); ok {
		if err := trackedrepo.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.owner": %w`, err)}
		}
	}
	if v, ok := tru.mutation.Name(); ok {
		if err := trackedrepo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.name": %w`, err)}
		}
	}
	if v, ok := tru.mutation.FullName(); ok {
		if err := trackedrepo.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.full_name": %w`, err)}
		}
	}
	if v, ok := tru.mutation.Description(); ok {
		if err := trackedrepo.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.description": %w`, err)}
		}
	}
	if v, ok := tru.mutation.Stars(); ok {
		if err := trackedrepo.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.stars": %w`, err)}
		}
	}
	if v, ok := tru.mutation.Forks(); ok {
		if err := trackedrepo.ForksValidator(v); err != nil {
			return &ValidationError{Name: "forks", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.forks": %w`, err)}
		}
	}
	if v, ok := tru.mutation.HTMLURL(); ok {
		if err := trackedrepo.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.html_url": %w`, err)}
		}
	}
	if v, ok := tru.mutation.Notes(); ok {
		if err := trackedrepo.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.notes": %w`, err)}
		}
	}
	return nil
}

func (tru *TrackedRepoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(trackedrepo.Table, trackedrepo.Columns, sqlgraph.NewFieldSpec(trackedrepo.FieldID, field.TypeInt))
	if ps := tru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tru.mutation.Owner(); ok {
		_spec.SetField(trackedrepo.FieldOwner, field.TypeString, value)
	}
	if value, ok := tru.mutation.Name(); ok {
		_spec.SetField(trackedrepo.FieldName, field.TypeString, value)
	}
	if value, ok := tru.mutation.FullName(); ok {
		_spec.SetField(trackedrepo.FieldFullName, field.TypeString, value)
	}
	if value, ok := tru.mutation.Description(); ok {
		_spec.SetField(trackedrepo.FieldDescription, field.TypeString, value)
	}
	if tru.mutation.DescriptionCleared() {
		_spec.ClearField(trackedrepo.FieldDescription, field.TypeString)
	}
	if value, ok := tru.mutation.Stars(); ok {
		_spec.SetField(trackedrepo.FieldStars, field.TypeInt, value)
	}
	if value, ok := tru.mutation.AddedStars(); ok {
		_spec.AddField(trackedrepo.FieldStars, field.TypeInt, value)
	}
	if value, ok := tru.mutation.Forks(); ok {
		_spec.SetField(trackedrepo.FieldForks, field.TypeInt, value)
	}
	if value, ok := tru.mutation.AddedForks(); ok {
		_spec.AddField(trackedrepo.FieldForks, field.TypeInt, value)
	}
	if value, ok := tru.mutation.Language(); ok {
		_spec.SetField(trackedrepo.FieldLanguage, field.TypeString, value)
	}
	if tru.mutation.LanguageCleared() {
		_spec.ClearField(trackedrepo.FieldLanguage, field.TypeString)
	}
	if value, ok := tru.mutation.HTMLURL(); ok {
		_spec.SetField(trackedrepo.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := tru.mutation.Notes(); ok {
		_spec.SetField(trackedrepo.FieldNotes, field.TypeString, value)
	}
	if tru.mutation.NotesCleared() {
		_spec.ClearField(trackedrepo.FieldNotes, field.TypeString)
	}
	if value, ok := tru.mutation.FetchedAt(); ok {
		_spec.SetField(trackedrepo.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := tru.mutation.UpdatedAt(); ok {
		_spec.SetField(trackedrepo.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trackedrepo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tru.mutation.done = true
	return n, nil
}

// TrackedRepoUpdateOne is the builder for updating a single TrackedRepo entity.
type TrackedRepoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrackedRepoMutation
}

// SetOwner sets the "owner" field.
func (truo *TrackedRepoUpdateOne) SetOwner(s string) *TrackedRepoUpdateOne {
	truo.mutation.SetOwner(s)
	return truo
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableOwner(s *string) *TrackedRepoUpdateOne {
	if s != nil {
		truo.SetOwner(*s)
	}
	return truo
}

// SetName sets the "name" field.
func (truo *TrackedRepoUpdateOne) SetName(s string) *TrackedRepoUpdateOne {
	truo.mutation.SetName(s)
	return truo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableName(s *string) *TrackedRepoUpdateOne {
	if s != nil {
		truo.SetName(*s)
	}
	return truo
}

// SetFullName sets the "full_name" field.
func (truo *TrackedRepoUpdateOne) SetFullName(s string) *TrackedRepoUpdateOne {
	truo.mutation.SetFullName(s)
	return truo
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableFullName(s *string) *TrackedRepoUpdateOne {
	if s != nil {
		truo.SetFullName(*s)
	}
	return truo
}

// SetDescription sets the "description" field.
func (truo *TrackedRepoUpdateOne) SetDescription(s string) *TrackedRepoUpdateOne {
	truo.mutation.SetDescription(s)
	return truo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableDescription(s *string) *TrackedRepoUpdateOne {
	if s != nil {
		truo.SetDescription(*s)
	}
	return truo
}

// ClearDescription clears the value of the "description" field.
func (truo *TrackedRepoUpdateOne) ClearDescription() *TrackedRepoUpdateOne {
	truo.mutation.ClearDescription()
	return truo
}

// SetStars sets the "stars" field.
func (truo *TrackedRepoUpdateOne) SetStars(i int) *TrackedRepoUpdateOne {
	truo.mutation.ResetStars()
	truo.mutation.SetStars(i)
	return truo
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableStars(i *int) *TrackedRepoUpdateOne {
	if i != nil {
		truo.SetStars(*i)
	}
	return truo
}

// AddStars adds i to the "stars" field.
func (truo *TrackedRepoUpdateOne) AddStars(i int) *TrackedRepoUpdateOne {
	truo.mutation.AddStars(i)
	return truo
}

// SetForks sets the "forks" field.
func (truo *TrackedRepoUpdateOne) SetForks(i int) *TrackedRepoUpdateOne {
	truo.mutation.ResetForks()
	truo.mutation.SetForks(i)
	return truo
}

// SetNillableForks sets the "forks" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableForks(i *int) *TrackedRepoUpdateOne {
	if i != nil {
		truo.SetForks(*i)
	}
	return truo
}

// AddForks adds i to the "forks" field.
func (truo *TrackedRepoUpdateOne) AddForks(i int) *TrackedRepoUpdateOne {
	truo.mutation.AddForks(i)
	return truo
}

// SetLanguage sets the "language" field.
func (truo *TrackedRepoUpdateOne) SetLanguage(s string) *TrackedRepoUpdateOne {
	truo.mutation.SetLanguage(s)
	return truo
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableLanguage(s *string) *TrackedRepoUpdateOne {
	if s != nil {
		truo.SetLanguage(*s)
	}
	return truo
}

// ClearLanguage clears the value of the "language" field.
func (truo *TrackedRepoUpdateOne) ClearLanguage() *TrackedRepoUpdateOne {
	truo.mutation.ClearLanguage()
	return truo
}

// SetHTMLURL sets the "html_url" field.
func (truo *TrackedRepoUpdateOne) SetHTMLURL(s string) *TrackedRepoUpdateOne {
	truo.mutation.SetHTMLURL(s)
	return truo
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableHTMLURL(s *string) *TrackedRepoUpdateOne {
	if s != nil {
		truo.SetHTMLURL(*s)
	}
	return truo
}

// SetNotes sets the "notes" field.
func (truo *TrackedRepoUpdateOne) SetNotes(s string) *TrackedRepoUpdateOne {
	truo.mutation.SetNotes(s)
	return truo
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableNotes(s *string) *TrackedRepoUpdateOne {
	if s != nil {
		truo.SetNotes(*s)
	}
	return truo
}

// ClearNotes clears the value of the "notes" field.
func (truo *TrackedRepoUpdateOne) ClearNotes() *TrackedRepoUpdateOne {
	truo.mutation.ClearNotes()
	return truo
}

// SetFetchedAt sets the "fetched_at" field.
func (truo *TrackedRepoUpdateOne) SetFetchedAt(t time.Time) *TrackedRepoUpdateOne {
	truo.mutation.SetFetchedAt(t)
	return truo
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (truo *TrackedRepoUpdateOne) SetNillableFetchedAt(t *time.Time) *TrackedRepoUpdateOne {
	if t != nil {
		truo.SetFetchedAt(*t)
	}
	return truo
}

// SetUpdatedAt sets the "updated_at" field.
func (truo *TrackedRepoUpdateOne) SetUpdatedAt(t time.Time) *TrackedRepoUpdateOne {
	truo.mutation.SetUpdatedAt(t)
	return truo
}

// Mutation returns the TrackedRepoMutation object of the builder.
func (truo *TrackedRepoUpdateOne) Mutation() *TrackedRepoMutation {
	return truo.mutation
}

// Where appends a list predicates to the TrackedRepoUpdate builder.
func (truo *TrackedRepoUpdateOne) Where(ps ...predicate.TrackedRepo) *TrackedRepoUpdateOne {
	truo.mutation.Where(ps...)
	return truo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (truo *TrackedRepoUpdateOne) Select(field string, fields ...string) *TrackedRepoUpdateOne {
	truo.fields = append([]string{field}, fields...)
	return truo
}

// Save executes the query and returns the updated TrackedRepo entity.
func (truo *TrackedRepoUpdateOne) Save(ctx context.Context) (*TrackedRepo, error) {
	truo.defaults()
	return withHooks(ctx, truo.sqlSave, truo.mutation, truo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (truo *TrackedRepoUpdateOne) SaveX(ctx context.Context) *TrackedRepo {
	node, err := truo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (truo *TrackedRepoUpdateOne) Exec(ctx context.Context) error {
	_, err := truo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (truo *TrackedRepoUpdateOne) ExecX(ctx context.Context) {
	if err := truo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (truo *TrackedRepoUpdateOne) defaults() {
	if _, ok := truo.mutation.UpdatedAt(); !ok {
		v := trackedrepo.UpdateDefaultUpdatedAt()
		truo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (truo *TrackedRepoUpdateOne) check() error {
	if v, ok := truo.mutation.Owner(); ok {
		if err := trackedrepo.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.owner": %w`, err)}
		}
	}
	if v, ok := truo.mutation.Name(); ok {
		if err := trackedrepo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.name": %w`, err)}
		}
	}
	if v, ok := truo.mutation.FullName(); ok {
		if err := trackedrepo.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.full_name": %w`, err)}
		}
	}
	if v, ok := truo.mutation.Description(); ok {
		if err := trackedrepo.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.description": %w`, err)}
		}
	}
	if v, ok := truo.mutation.Stars(); ok {
		if err := trackedrepo.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.stars": %w`, err)}
		}
	}
	if v, ok := truo.mutation.Forks(); ok {
		if err := trackedrepo.ForksValidator(v); err != nil {
			return &ValidationError{Name: "forks", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.forks": %w`, err)}
		}
	}
	if v, ok := truo.mutation.HTMLURL(); ok {
		if err := trackedrepo.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.html_url": %w`, err)}
		}
	}
	if v, ok := truo.mutation.Notes(); ok {
		if err := trackedrepo.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "TrackedRepo.notes": %w`, err)}
		}
	}
	return nil
}

func (truo *TrackedRepoUpdateOne) sqlSave(ctx context.Context) (_node *TrackedRepo, err error) {
	if err := truo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trackedrepo.Table, trackedrepo.Columns, sqlgraph.NewFieldSpec(trackedrepo.FieldID, field.TypeInt))
	id, ok := truo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TrackedRepo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := truo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trackedrepo.FieldID)
		for _, f := range fields {
			if !trackedrepo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trackedrepo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := truo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := truo.mutation.Owner(); ok {
		_spec.SetField(trackedrepo.FieldOwner, field.TypeString, value)
	}
	if value, ok := truo.mutation.Name(); ok {
		_spec.SetField(trackedrepo.FieldName, field.TypeString, value)
	}
	if value, ok := truo.mutation.FullName(); ok {
		_spec.SetField(trackedrepo.FieldFullName, field.TypeString, value)
	}
	if value, ok := truo.mutation.Description(); ok {
		_spec.SetField(trackedrepo.FieldDescription, field.TypeString, value)
	}
	if truo.mutation.DescriptionCleared() {
		_spec.ClearField(trackedrepo.FieldDescription, field.TypeString)
	}
	if value, ok := truo.mutation.Stars(); ok {
		_spec.SetField(trackedrepo.FieldStars, field.TypeInt, value)
	}
	if value, ok := truo.mutation.AddedStars(); ok {
		_spec.AddField(trackedrepo.FieldStars, field.TypeInt, value)
	}
	if value, ok := truo.mutation.Forks(); ok {
		_spec.SetField(trackedrepo.FieldForks, field.TypeInt, value)
	}
	if value, ok := truo.mutation.AddedForks(); ok {
		_spec.AddField(trackedrepo.FieldForks, field.TypeInt, value)
	}
	if value, ok := truo.mutation.Language(); ok {
		_spec.SetField(trackedrepo.FieldLanguage, field.TypeString, value)
	}
	if truo.mutation.LanguageCleared() {
		_spec.ClearField(trackedrepo.FieldLanguage, field.TypeString)
	}
	if value, ok := truo.mutation.HTMLURL(); ok {
		_spec.SetField(trackedrepo.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := truo.mutation.Notes(); ok {
		_spec.SetField(trackedrepo.FieldNotes, field.TypeString, value)
	}
	if truo.mutation.NotesCleared() {
		_spec.ClearField(trackedrepo.FieldNotes, field.TypeString)
	}
	if value, ok := truo.mutation.FetchedAt(); ok {
		_spec.SetField(trackedrepo.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := truo.mutation.UpdatedAt(); ok {
		_spec.SetField(trackedrepo.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TrackedRepo{config: truo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, truo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trackedrepo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	truo.mutation.done = true
	return _node, nil
}
