// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ilyas/repository-tracker-app/backend/ent/trackedrepo"
)

// TrackedRepo is the model entity for the TrackedRepo schema.
type TrackedRepo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Owner holds the value of the "owner" field.
	Owner string `json:"owner,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// FullName holds the value of the "full_name" field.
	FullName string `json:"full_name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Stars holds the value of the "stars" field.
	Stars int `json:"stars,omitempty"`
	// Forks holds the value of the "forks" field.
	Forks int `json:"forks,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// HTMLURL holds the value of the "html_url" field.
	HTMLURL string `json:"html_url,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// FetchedAt holds the value of the "fetched_at" field.
	FetchedAt time.Time `json:"fetched_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TrackedRepo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trackedrepo.FieldID, trackedrepo.FieldStars, trackedrepo.FieldForks:
			values[i] = new(sql.NullInt64)
		case trackedrepo.FieldOwner, trackedrepo.FieldName, trackedrepo.FieldFullName, trackedrepo.FieldDescription, trackedrepo.FieldLanguage, trackedrepo.FieldHTMLURL, trackedrepo.FieldNotes:
			values[i] = new(sql.NullString)
		case trackedrepo.FieldFetchedAt, trackedrepo.FieldCreatedAt, trackedrepo.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TrackedRepo fields.
func (tr *TrackedRepo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trackedrepo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tr.ID = int(value.Int64)
		case trackedrepo.FieldOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner", values[i])
			} else if value.Valid {
				tr.Owner = value.String
			}
		case trackedrepo.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				tr.Name = value.String
			}
		case trackedrepo.FieldFullName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_name", values[i])
			} else if value.Valid {
				tr.FullName = value.String
			}
		case trackedrepo.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				tr.Description = value.String
			}
		case trackedrepo.FieldStars:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stars", values[i])
			} else if value.Valid {
				tr.Stars = int(value.Int64)
			}
		case trackedrepo.FieldForks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field forks", values[i])
			} else if value.Valid {
				tr.Forks = int(value.Int64)
			}
		case trackedrepo.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				tr.Language = value.String
			}
		case trackedrepo.FieldHTMLURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field html_url", values[i])
			} else if value.Valid {
				tr.HTMLURL = value.String
			}
		case trackedrepo.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				tr.Notes = value.String
			}
		case trackedrepo.FieldFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fetched_at", values[i])
			} else if value.Valid {
				tr.FetchedAt = value.Time
			}
		case trackedrepo.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tr.CreatedAt = value.Time
			}
		case trackedrepo.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tr.UpdatedAt = value.Time
			}
		default:
			tr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TrackedRepo.
// This includes values selected through modifiers, order, etc.
func (tr *TrackedRepo) Value(name string) (ent.Value, error) {
	return tr.selectValues.Get(name)
}

// Update returns a builder for updating this TrackedRepo.
// Note that you need to call TrackedRepo.Unwrap() before calling this method if this TrackedRepo
// was returned from a transaction, and the transaction was committed or rolled back.
func (tr *TrackedRepo) Update() *TrackedRepoUpdateOne {
	return NewTrackedRepoClient(tr.config).UpdateOne(tr)
}

// Unwrap unwraps the TrackedRepo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tr *TrackedRepo) Unwrap() *TrackedRepo {
	_tx, ok := tr.config.driver.(*txDriver)
	if !ok {
		panic("ent: TrackedRepo is not a transactional entity")
	}
	tr.config.driver = _tx.drv
	return tr
}

// String implements the fmt.Stringer.
func (tr *TrackedRepo) String() string {
	var builder strings.Builder
	builder.WriteString("TrackedRepo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tr.ID))
	builder.WriteString("owner=")
	builder.WriteString(tr.Owner)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(tr.Name)
	builder.WriteString(", ")
	builder.WriteString("full_name=")
	builder.WriteString(tr.FullName)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(tr.Description)
	builder.WriteString(", ")
	builder.WriteString("stars=")
	builder.WriteString(fmt.Sprintf("%v", tr.Stars))
	builder.WriteString(", ")
	builder.WriteString("forks=")
	builder.WriteString(fmt.Sprintf("%v", tr.Forks))
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(tr.Language)
	builder.WriteString(", ")
	builder.WriteString("html_url=")
	builder.WriteString(tr.HTMLURL)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(tr.Notes)
	builder.WriteString(", ")
	builder.WriteString("fetched_at=")
	builder.WriteString(tr.FetchedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(tr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tr.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TrackedRepos is a parsable slice of TrackedRepo.
type TrackedRepos []*TrackedRepo
