// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ilyas/repository-tracker-app/backend/ent/predicate"
	"github.com/ilyas/repository-tracker-app/backend/ent/trackedrepo"
)

// TrackedRepoQuery is the builder for querying TrackedRepo entities.
type TrackedRepoQuery struct {
	config
	ctx        *QueryContext
	order      []trackedrepo.OrderOption
	inters     []Interceptor
	predicates []predicate.TrackedRepo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrackedRepoQuery builder.
func (trq *TrackedRepoQuery) Where(ps ...predicate.TrackedRepo) *TrackedRepoQuery {
	trq.predicates = append(trq.predicates, ps...)
	return trq
}

// Limit the number of records to be returned by this query.
func (trq *TrackedRepoQuery) Limit(limit int) *TrackedRepoQuery {
	trq.ctx.Limit = &limit
	return trq
}

// Offset to start from.
func (trq *TrackedRepoQuery) Offset(offset int) *TrackedRepoQuery {
	trq.ctx.Offset = &offset
	return trq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (trq *TrackedRepoQuery) Unique(unique bool) *TrackedRepoQuery {
	trq.ctx.Unique = &unique
	return trq
}

// Order specifies how the records should be ordered.
func (trq *TrackedRepoQuery) Order(o ...trackedrepo.OrderOption) *TrackedRepoQuery {
	trq.order = append(trq.order, o...)
	return trq
}

// First returns the first TrackedRepo entity from the query.
// Returns a *NotFoundError when no TrackedRepo was found.
func (trq *TrackedRepoQuery) First(ctx context.Context) (*TrackedRepo, error) {
	nodes, err := trq.Limit(1).All(setContextOp(ctx, trq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trackedrepo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (trq *TrackedRepoQuery) FirstX(ctx context.Context) *TrackedRepo {
	node, err := trq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TrackedRepo ID from the query.
// Returns a *NotFoundError when no TrackedRepo ID was found.
func (trq *TrackedRepoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = trq.Limit(1).IDs(setContextOp(ctx, trq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trackedrepo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (trq *TrackedRepoQuery) FirstIDX(ctx context.Context) int {
	id, err := trq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TrackedRepo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TrackedRepo entity is found.
// Returns a *NotFoundError when no TrackedRepo entities are found.
func (trq *TrackedRepoQuery) Only(ctx context.Context) (*TrackedRepo, error) {
	nodes, err := trq.Limit(2).All(setContextOp(ctx, trq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trackedrepo.Label}
	default:
		return nil, &NotSingularError{trackedrepo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (trq *TrackedRepoQuery) OnlyX(ctx context.Context) *TrackedRepo {
	node, err := trq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TrackedRepo ID in the query.
// Returns a *NotSingularError when more than one TrackedRepo ID is found.
// Returns a *NotFoundError when no entities are found.
func (trq *TrackedRepoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = trq.Limit(2).IDs(setContextOp(ctx, trq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trackedrepo.Label}
	default:
		err = &NotSingularError{trackedrepo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (trq *TrackedRepoQuery) OnlyIDX(ctx context.Context) int {
	id, err := trq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TrackedRepos.
func (trq *TrackedRepoQuery) All(ctx context.Context) ([]*TrackedRepo, error) {
	ctx = setContextOp(ctx, trq.ctx, "All")
	if err := trq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TrackedRepo, *TrackedRepoQuery]()
	return withInterceptors[[]*TrackedRepo](ctx, trq, qr, trq.inters)
}

// AllX is like All, but panics if an error occurs.
func (trq *TrackedRepoQuery) AllX(ctx context.Context) []*TrackedRepo {
	nodes, err := trq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TrackedRepo IDs.
func (trq *TrackedRepoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if trq.ctx.Unique == nil && trq.path != nil {
		trq.Unique(true)
	}
	ctx = setContextOp(ctx, trq.ctx, "IDs")
	if err = trq.Select(trackedrepo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (trq *TrackedRepoQuery) IDsX(ctx context.Context) []int {
	ids, err := trq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (trq *TrackedRepoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, trq.ctx, "Count")
	if err := trq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, trq, querierCount[*TrackedRepoQuery](), trq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (trq *TrackedRepoQuery) CountX(ctx context.Context) int {
	count, err := trq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (trq *TrackedRepoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, trq.ctx, "Exist")
	switch _, err := trq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (trq *TrackedRepoQuery) ExistX(ctx context.Context) bool {
	exist, err := trq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrackedRepoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (trq *TrackedRepoQuery) Clone() *TrackedRepoQuery {
	if trq == nil {
		return nil
	}
	return &TrackedRepoQuery{
		config:     trq.config,
		ctx:        trq.ctx.Clone(),
		order:      append([]trackedrepo.OrderOption{}, trq.order...),
		inters:     append([]Interceptor{}, trq.inters...),
		predicates: append([]predicate.TrackedRepo{}, trq.predicates...),
		// clone intermediate query.
		sql:  trq.sql.Clone(),
		path: trq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Owner string `json:"owner,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TrackedRepo.Query().
//		GroupBy(trackedrepo.FieldOwner).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (trq *TrackedRepoQuery) GroupBy(field string, fields ...string) *TrackedRepoGroupBy {
	trq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrackedRepoGroupBy{build: trq}
	grbuild.flds = &trq.ctx.Fields
	grbuild.label = trackedrepo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Owner string `json:"owner,omitempty"`
//	}
//
//	client.TrackedRepo.Query().
//		Select(trackedrepo.FieldOwner).
//		Scan(ctx, &v)
func (trq *TrackedRepoQuery) Select(fields ...string) *TrackedRepoSelect {
	trq.ctx.Fields = append(trq.ctx.Fields, fields...)
	sbuild := &TrackedRepoSelect{TrackedRepoQuery: trq}
	sbuild.label = trackedrepo.Label
	sbuild.flds, sbuild.scan = &trq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrackedRepoSelect configured with the given aggregations.
func (trq *TrackedRepoQuery) Aggregate(fns ...AggregateFunc) *TrackedRepoSelect {
	return trq.Select().Aggregate(fns...)
}

func (trq *TrackedRepoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range trq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, trq); err != nil {
				return err
			}
		}
	}
	for _, f := range trq.ctx.Fields {
		if !trackedrepo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if trq.path != nil {
		prev, err := trq.path(ctx)
		if err != nil {
			return err
		}
		trq.sql = prev
	}
	return nil
}

func (trq *TrackedRepoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TrackedRepo, error) {
	var (
		nodes = []*TrackedRepo{}
		_spec = trq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TrackedRepo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TrackedRepo{config: trq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, trq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (trq *TrackedRepoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := trq.querySpec()
	_spec.Node.Columns = trq.ctx.Fields
	if len(trq.ctx.Fields) > 0 {
		_spec.Unique = trq.ctx.Unique != nil && *trq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, trq.driver, _spec)
}

func (trq *TrackedRepoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(trackedrepo.Table, trackedrepo.Columns, sqlgraph.NewFieldSpec(trackedrepo.FieldID, field.TypeInt))
	_spec.From = trq.sql
	if unique := trq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if trq.path != nil {
		_spec.Unique = true
	}
	if fields := trq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trackedrepo.FieldID)
		for i := range fields {
			if fields[i] != trackedrepo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := trq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := trq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := trq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := trq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (trq *TrackedRepoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(trq.driver.Dialect())
	t1 := builder.Table(trackedrepo.Table)
	columns := trq.ctx.Fields
	if len(columns) == 0 {
		columns = trackedrepo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if trq.sql != nil {
		selector = trq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if trq.ctx.Unique != nil && *trq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range trq.predicates {
		p(selector)
	}
	for _, p := range trq.order {
		p(selector)
	}
	if offset := trq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := trq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrackedRepoGroupBy is the group-by builder for TrackedRepo entities.
type TrackedRepoGroupBy struct {
	selector
	build *TrackedRepoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (trgb *TrackedRepoGroupBy) Aggregate(fns ...AggregateFunc) *TrackedRepoGroupBy {
	trgb.fns = append(trgb.fns, fns...)
	return trgb
}

// Scan applies the selector query and scans the result into the given value.
func (trgb *TrackedRepoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, trgb.build.ctx, "GroupBy")
	if err := trgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrackedRepoQuery, *TrackedRepoGroupBy](ctx, trgb.build, trgb, trgb.build.inters, v)
}

func (trgb *TrackedRepoGroupBy) sqlScan(ctx context.Context, root *TrackedRepoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(trgb.fns))
	for _, fn := range trgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*trgb.flds)+len(trgb.fns))
		for _, f := range *trgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*trgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrackedRepoSelect is the builder for selecting fields of TrackedRepo entities.
type TrackedRepoSelect struct {
	*TrackedRepoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (trs *TrackedRepoSelect) Aggregate(fns ...AggregateFunc) *TrackedRepoSelect {
	trs.fns = append(trs.fns, fns...)
	return trs
}

// Scan applies the selector query and scans the result into the given value.
func (trs *TrackedRepoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, trs.ctx, "Select")
	if err := trs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrackedRepoQuery, *TrackedRepoSelect](ctx, trs.TrackedRepoQuery, trs, trs.inters, v)
}

func (trs *TrackedRepoSelect) sqlScan(ctx context.Context, root *TrackedRepoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(trs.fns))
	for _, fn := range trs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*trs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
