// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TrackedReposColumns holds the columns for the "tracked_repos" table.
	TrackedReposColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "owner", Type: field.TypeString, Size: 100},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "full_name", Type: field.TypeString, Unique: true, Size: 201},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024, Default: ""},
		{Name: "stars", Type: field.TypeInt, Default: 0},
		{Name: "language", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "html_url", Type: field.TypeString},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2000, Default: ""},
		{Name: "fetched_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TrackedReposTable holds the schema information for the "tracked_repos" table.
	TrackedReposTable = &schema.Table{
		Name:       "tracked_repos",
		Columns:    TrackedReposColumns,
		PrimaryKey: []*schema.Column{TrackedReposColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "trackedrepo_language",
				Unique:  false,
				Columns: []*schema.Column{TrackedReposColumns[6]},
			},
			{
				Name:    "trackedrepo_stars",
				Unique:  false,
				Columns: []*schema.Column{TrackedReposColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TrackedReposTable,
	}
)

func init() {
}
